# Generated by Django 2.1.5 on 2019-01-11 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accomplishment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('portfolio_item', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='portfolio.PortfolioItem')),
            ],
        ),
    ]
