# Generated by Django 2.1.5 on 2019-01-13 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_portfolioitem_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='ended_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='started_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
